
## PRACTICE 1

Find the max weight for the two treatment groups

```{r}
# ANSWER
## treatment 1
max(plants$weight[plants$group=="trt1"])

## treatment 2
max(plants$weight[plants$group=="trt2"])
```


## PRACTICE 2

Another example, with a different dataset, iris. Find the mean petal length for each species

```{r}
## create an empty dataframe
meandf = NULL

## for loop
for (i in unique(iris$Species)){
  
  ## operation 
  x <- mean(iris$Petal.Length[iris$Species == i])
  
  ## make x into a dataframe to be able to combine it to the existing output dataframe
  x = as.data.frame(x)
  
  ## add a group indicator to x
  x$iris_species = i
  
  ## add current loop iteration output to exisiting output
  meandf = rbind.fill(meandf, x)
  
}

```


## PRACTICE 3

```{r}
## seep what the specis are
print(c(unique(iris$Species)))

## binary variable
iris$v_start <- NA

## for loop
for (i in 1:nrow(iris)) {
  if (iris$Species[i] == 'setosa') {
    iris$v_start[i] = 0 ## 0 for no v
  } else {
    iris$v_start[i] = 1 ## 1 for v
  }
}


```


